app.get("/users", (req,res) => {
const users = [ 
    {
        id: 1,
        firstName: 'Martin',
        lastName: 'Matin',
        email: 'martin@matin.fr',
        password: 'martinmatin',
        phone: '06000000',
        creationDate: '2020-12-28T22:00:00.000Z',
        role: 'Customer',
    },
    {
        id: 2,
        firstName: 'Scooby',
        lastName: 'Doo',
        email: 'scooby@doo.fr',
        password: 'scoobydoo',
        phone: '06000000',
        creationDate: '2020-12-28T22:00:00.000Z',
        role: 'Customer',
    },
    {
        id: 3,
        firstName: 'Howard',
        lastName: 'Lovecraft',
        email: 'howard@lovecraft.fr',
        password: 'howardlovecraft',
        phone: '06000000',
        creationDate: '2020-12-28T22:00:00.000Z',
        role: 'Customer',
    },
    {
        id: 4,
        firstName: 'Paimon',
        lastName: 'Cassecroute',
        email: 'test@test.fr',
        password: 'testtest',
        phone: '09000000',
        creationDate: '2020-12-28T22:00:00.000Z',
        role: 'Customer',
    },
    {
        id: 5,
        firstName: 'Mario',
        lastName: 'Bros',
        email: 'mario@bros.fr',
        password: 'mariobros',
        phone: '06000000',
        creationDate: '2020-12-28T22:00:00.000Z',
        role: 'Customer',
    },
    {
        id: 6,
        firstName: 'Kim',
        lastName: 'Possible',
        email: 'kim@possible.fr',
        password: 'kimpossible',
        phone: '06000000',
        creationDate: '2020-12-28T22:00:00.000Z',
        role: 'Customer',
    },
];
})
module.exports = users